name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: setup docker
        uses: docker-practice/actions-setup-docker@master

      - name: build docker image
        run: |
                    docker build -t ghcr.io/ro6it/headlamp-plugins:latest ./

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push docker image
        run: |
                    docker push ghcr.io/ro6it/headlamp-plugins:latest
